### ISSUE TITLE
Ошибка формата потока

### ISSUE THREAD

**Issue by korotovskih** [1C-Company/docker_fresh#12]
![image](https://user-images.githubusercontent.com/34188696/98018712-ac196980-1e22-11eb-83e8-42a5f5841d79.png)

Проблема в создавшейся базе, я получаю ошибку при попытке подключиться конфигуратором в созданную базу.
```
CREATEINFOBASE "Srvr=srv;Ref=sa4;DBMS=PostgreSQL;DBSrvr=/tmp/postgresql/socket;DB=sa4;DBUID=postgres;LicDstr=Y;Locale=ru_RU;CrSQLDB=Y;SchJobDn=N;"
```

```
47:13.608000-0,EXCP,1,process=1cv8,OSThread=693,Exception=d294e384-7ea6-49c6-be96-f3a6e3de1242,Descr='LoadComponent(cfgtest):
d294e384-7ea6-49c6-be96-f3a6e3de1242: Ошибка загрузки компоненты cfgtest: '
47:14.019000-0,EXCP,2,process=1cv8,OSThread=693,Exception=9db1fa37-b455-4f3f-b8dd-7de0ea7d6da3,Descr="./src/ClientFileCacheImpl.cpp(280):
9db1fa37-b455-4f3f-b8dd-7de0ea7d6da3: Файл не обнаружен 'v8stg64://c:/1/DynamicalWorkCache': ./src/Storage64.cpp(3077)"
47:14.020002-0,EXCP,2,process=1cv8,OSThread=693,Exception=9db1fa37-b455-4f3f-b8dd-7de0ea7d6da3,Descr="./src/ClientFileCacheImpl.cpp(280):
9db1fa37-b455-4f3f-b8dd-7de0ea7d6da3: Файл не обнаружен 'v8stg64://c:/3/DynamicalWorkCache': ./src/Storage64.cpp(3077)"
47:15.737001-0,EXCP,1,process=1cv8,OSThread=693,Exception=e88a796d-7758-48a7-9ba7-781e269e9aa4,Descr='./src/ExceptionWriterUIImpl.cpp(224), shown to the user:
e88a796d-7758-48a7-9ba7-781e269e9aa4: Ошибка формата потока'
```

**Comment by WizaXxX** [comment]
Попробуйте в момент возникновения ошибки подключиться к контейнеру командой `docker exec -it ИмяКонтейнера bash` и там фактически посмотреть на файл `/mnt/smtl.cf` хотя бы на его размер. Возможно что то идет не так в момент монтирования каталогов

**Comment by DmitriyKorotovskih** [comment]
> Попробуйте в момент возникновения ошибки подключиться к контейнеру командой `docker exec -it ИмяКонтейнера bash` и там фактически посмотреть на файл `/mnt/smtl.cf` хотя бы на его размер. Возможно что то идет не так в момент монтирования каталогов

Я тоже сперва грешил на smtl.cf, но в итоге выяснил что дело в любой базе созданной в контейнере db.
Я пробовал создавать на нем базы, не относящие к сценарию - они создавались, но при подключении к ним возникает ошибка формата потока.

**Comment by WizaXxX** [comment]
А какая версия платформы? Может попробовать другую?

**Comment by DmitriyKorotovskih** [comment]
> А какая версия платформы? Может попробовать другую?
я собирал с 8.3.15.1869 (как в ридми) и 8.3.17.1549 - аналогично

**Comment by DmitriyKorotovskih** [comment]
я мог бы сохранить собранные образы и отправить вам, учитывая содержимое я их не прикладываю к обращению

**Comment by WizaXxX** [comment]
А какая ОС используется?
Лучше в телеграмм тогда прислать ссылку.
https://t.me/wizaxxx

**Comment by DmitriyKorotovskih** [comment]
> А какая ОС используется?
речь идет о docker windows, wsl2 based engine

> Лучше в телеграмм тогда прислать ссылку.
> https://t.me/wizaxxx
хорошо - отправлю туда

**Comment by WizaXxX** [comment]
На wsl2 не тестировалось. А может есть возможность проверить без wsl?

**Comment by DmitriyKorotovskih** [comment]
> На wsl2 не тестировалось. А может есть возможность проверить без wsl?

Да, я мог бы проверить, если нет каких-то иных соображений о причине

**Comment by WizaXxX** [comment]
Пока что нет, но вы все равно пришлите образы.
Попробую их например на linux запустить

**Comment by DmitriyKorotovskih** [comment]
Мой докер
```Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:00:27 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
Если клиент и сервер докера запущенны на одном linux хосте - ошибка не воспроизводится.
Если клиент работает на win, а сервер в wls2 дистрибутиве - воспроизводится ошибка формата потока.
Окружение для воспроизведения отправил мейнтейнеру.
Еще я успел погрешить на вольюмы, сделал компоуз без них, подключаясь к ПГ через порт, но это тоже не помогло.

**Comment by WizaXxX** [comment]
Установил WSL2. Все равно ошибка не воспроизводится :( 
Образы использовал именно из архива. 

Попробовал подключиться с той же машины с на которой стоит docker. Получил ошибку https://github.com/1C-Company/docker_fresh/issues/7
Попробовал подключиться с Mac OS, подключился нормально.

Правильно ли я понимаю что у вас ошибка появляется именно тогда, когда вы подключаете конфигуратором к базе с того же ПК на котором и docker стоит?

**Comment by DmitriyKorotovskih** [comment]
> Правильно ли я понимаю что у вас ошибка появляется именно тогда, когда вы подключаете конфигуратором к базе с того же ПК на котором и docker стоит?

Нет, ошибка возникает при любой операции после создания базы. на скрине я это делал подключившись в контейнер через vnc.

> Установил WSL2. Все равно ошибка не воспроизводится :(

а вы включили опцию? 
![image](https://user-images.githubusercontent.com/34188696/99684238-08c38800-2aa3-11eb-9a06-868dbce05bfc.png)

если сделать 
```
docker version
```
будет видно
```
Client: Docker Engine - Community
 OS/Arch:           windows/amd64
Server: Docker Engine - Community
 Engine:
  OS/Arch:          linux/amd64
```

мне кажется ошибка связана с тем, что клиент и сервер докера - разные хосты, и существует какая-то такая особенность в сетевом взаимодействии, что pgpro и клиент/сервер 1с не могут найти общий язык

**Comment by WizaXxX** [comment]
> Нет, ошибка возникает при любой операции после создания базы. на скрине я это делал подключившись в контейнер через vnc.  

В самом контейнере тоже конектился конфигуратором, проблемы нет.

> а вы включили опцию?

Конечно.
![image](https://user-images.githubusercontent.com/8429673/99684995-25f05a80-2a93-11eb-9c45-58726b100c1b.png)

> мне кажется ошибка связана с тем, что клиент и сервер докера - разные хосты, и существует какая-то такая особенность в сетевом взаимодействии, что pgpro и клиент/сервер 1с не могут найти общий язык

Ну клиентская часть docker не особо то и важна как мне кажется. 
Я все делал из под ubuntu в wsl. Но могу показать оба результата
![image](https://user-images.githubusercontent.com/8429673/99685627-d65e5e80-2a93-11eb-8f6d-85c298fce0f5.png)


А вы запускали стенд из под wsl или в cmd/PowerShell?

**Comment by DmitriyKorotovskih** [comment]
> А вы запускали стенд из под wsl или в cmd/PowerShell?

у меня из cmd и из убунты под всл воспроизводилось =(

**Comment by WizaXxX** [comment]
А если создать пустую ИБ без указания cf файла, конфигуратор открывается?

**Comment by DmitriyKorotovskih** [comment]
> А если создать пустую ИБ без указания cf файла, конфигуратор открывается?

не открывается

**Comment by WizaXxX** [comment]
Может быть переустановка docket desktop поможет? 
У меня просто кончились идеи... куда ещё можно капнуть:(

**Comment by DmitriyKorotovskih** [comment]
> Может быть переустановка docket desktop поможет?
> У меня просто кончились идеи... куда ещё можно капнуть:(

9 из 10 дело где-то между pgpro и 1с которые почему-то ведут себя плохо в окружении, мне не-то что бы чешется колется это через wsl, я пока проверял, пришел к желаемому результата в hyper-v.

Возможно у вас есть коллеги которые умеют транслировать ошибку формата потока в конкретную неисправность, ее раскрытие может иметь , в том числе, продуктовую ценность?

**Comment by WizaXxX** [comment]
Как оказалось проблема не в этом.
После долгих попыток выяснилось что проблема была в пробросе каталога кластера 
`- ./artifacts/srv/data:/var/lib/1c/data`
переделал на использование volume и ошибка ушла.
