### ISSUE TITLE
Ошибка запуска

### ISSUE THREAD

**Issue by svok2005** [1C-Company/docker_fresh#19]
При запуске python3 start.py -new -h demo -debug выдает [ошибку.
https://yadi.sk/i/Q7Ad2dgW6rRfyw
https://yadi.sk/i/DY0tGqSrf0Xr_A

**Comment by WizaXxX** [comment]
Добрый день. Покажите пожалуйста что у вас в справочнике Шлюзы приложений.
Такое ощущение что проблема была раньше. Первоначальное заполнение Менеджера сервиса выполнилось нормально?

**Comment by svok2005** [comment]
Fresh is starting at 2021-05-13 19:33:27.148351
Down all conteiners ... done
host name is demo.1cfresh.dev
Set full hostname ... done
path to 1C: /opt/1C/v8.3/x86_64/
Getting path to 1C ... done
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine rm -rf /out_files/workdir
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine mkdir -p /out_files/workdir/mnt
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine mkdir -p /out_files/workdir/artifacts/web/conf
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "cp /out_files/conf/web/httpd.conf /out_files/workdir/artifacts/web/conf/httpd.conf"
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "cp /out_files/distr/*.cf /out_files/workdir/mnt/"
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "cp /out_files/distr/*.cfe /out_files/workdir/mnt/"
cp: can't stat '/out_files/distr/*.cfe': No such file or directory
Renew wordir ... done
Get configuration data ... done
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine mkdir -p /out_files/workdir/artifacts/nginx/conf/
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "cp -r /out_files/conf/nginx/* /out_files/workdir/artifacts/nginx/conf/"
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "sed -i 's/hosthosthost/demo.1cfresh.dev/g' /out_files/workdir/artifacts/nginx/conf/*.conf"
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "sed -i 's/sitesitesite/site.demo.1cfresh.dev/g' /out_files/workdir/artifacts/nginx/conf/*.conf"
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "sed -i 's/webwebweb/web.demo.1cfresh.dev/g' /out_files/workdir/artifacts/nginx/conf/*.conf"
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "sed -i 's/gategategate/gate.demo.1cfresh.dev/g' /out_files/workdir/artifacts/nginx/conf/*.conf"
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "sed -i 's/sitesitesite/site.demo.1cfresh.dev/g' /out_files/workdir/artifacts/nginx/conf/conf.d/*.conf"
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "sed -i 's/hosthosthost/demo.1cfresh.dev/g' /out_files/workdir/artifacts/nginx/conf/conf.d/*.conf"
Renew nginx files ... done
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine cp /out_files/docker-compose_pattern.yml /out_files/workdir/docker-compose.yml
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "sed -i 's/HOSTNAMEREPLACE/demo.1cfresh.dev/' /out_files/workdir//*.yml"
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "sed -i 's/PATH_TO_1C_REPLACE/\/opt\/1C\/v8.3\/x86_64\//' /out_files/workdir//*.yml"
Renew docker-compose file ... done
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine rm -rf /out_files/workdir/mnt/other-files/
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine cp -r /out_files/other_files/ /out_files/workdir/mnt/other-files/
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "sed -i 's/HOSTNAMEREPLACE/demo.1cfresh.dev/' /out_files/workdir/mnt/other-files/vrd/*.vrd"
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine sh -c "sed -i 's/HOSTNAMEREPLACE/demo.1cfresh.dev/' /out_files/workdir/mnt/other-files/params.json"
Renew other-files ... done
docker volume rm workdir_1c_pg_data
Error: No such volume: workdir_1c_pg_data
docker volume rm workdir_1c_pg_socket
Error: No such volume: workdir_1c_pg_socket
docker volume rm workdir_1c_server_data
Error: No such volume: workdir_1c_server_data
Delete volumes ... done
docker-compose -f workdir/docker-compose.yml up -d db srv ras web gate s3
Creating network "workdir_default" with the default driver
Creating volume "workdir_1c_pg_data" with default driver
Creating volume "workdir_1c_pg_socket" with default driver
Creating volume "workdir_1c_server_data" with default driver
Creating ras.demo.1cfresh.dev ... done
Creating s3.1cfresh.dev       ... done
Creating db.demo.1cfresh.dev  ... done
Creating srv.demo.1cfresh.dev ... done
Creating web.demo.1cfresh.dev  ... done
Creating gate.demo.1cfresh.dev ... done
docker exec -t db.demo.1cfresh.dev /wait_postgres.sh
/tmp:5432 - accepting connections
Waiting for postgres ... done
docker run --rm -v /home/svok/docker_fresh/:/out_files alpine mkdir /out_files/workdir/artifacts/s3/files
Create new bucket to 1C ... done
docker exec web.demo.1cfresh.dev /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir a/adm -dir /var/www/a/adm -connstr "Srvr=srv;Ref=sm;" -confpath "/etc/httpd/conf/httpd.conf" -descriptor "/mnt/other-files/vrd/zoneless.vrd"
Publish services
Публикация выполнена
docker exec web.demo.1cfresh.dev /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir int/sm -dir /var/www/int/sm -connstr "Srvr=srv;Ref=sm;" -confpath "/etc/httpd/conf/httpd.conf" -descriptor "/mnt/other-files/vrd/zoneless.vrd"

Публикация выполнена
docker exec web.demo.1cfresh.dev /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir a/smtl -dir /var/www/a/smtl -connstr "Srvr=srv;Ref=smtl;" -confpath "/etc/httpd/conf/httpd.conf" -descriptor "/mnt/other-files/vrd/withzone.vrd"

Публикация выполнена
docker exec web.demo.1cfresh.dev /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir int/smtl -dir /var/www/int/smtl -connstr "Srvr=srv;Ref=smtl;" -confpath "/etc/httpd/conf/httpd.conf" -descriptor "/mnt/other-files/vrd/zoneless.vrd"
Publish services .
Публикация выполнена
docker exec web.demo.1cfresh.dev /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir a/sa -dir /var/www/a/sa -connstr "Srvr=srv;Ref=sa;" -confpath "/etc/httpd/conf/httpd.conf" -descriptor "/mnt/other-files/vrd/zoneless.vrd"

Публикация выполнена
docker exec web.demo.1cfresh.dev /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir int/sa -dir /var/www/int/sa -connstr "Srvr=srv;Ref=sa;" -confpath "/etc/httpd/conf/httpd.conf" -descriptor "/mnt/other-files/vrd/zoneless.vrd"

Публикация выполнена
docker exec web.demo.1cfresh.dev /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir int/am -dir /var/www/int/am -connstr "Srvr=srv;Ref=am;" -confpath "/etc/httpd/conf/httpd.conf" -descriptor "/mnt/other-files/vrd/zoneless.vrd"
Publish services ..
Публикация выполнена
docker exec web.demo.1cfresh.dev /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir a/openid -dir /var/www/a/openid -connstr "Srvr=srv;Ref=sm;" -confpath "/etc/httpd/conf/httpd.conf" -descriptor "/mnt/other-files/vrd/openid.vrd"

Публикация выполнена
docker exec web.demo.1cfresh.dev /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir int/sc -dir /var/www/int/sc -connstr "Srvr=srv;Ref=sm;Usr=SessionControl;Pwd=123Qwer;" -confpath "/etc/httpd/conf/httpd.conf" -descriptor "/mnt/other-files/vrd/sessioncontrol.vrd"

Публикация выполнена
docker exec web.demo.1cfresh.dev /opt/1C/v8.3/x86_64/webinst -apache24 -wsdir int/extreg -dir /var/www/int/extreg -connstr "Srvr=srv;Ref=sm;Usr=ExtReg;Pwd=123Qwer;" -confpath "/etc/httpd/conf/httpd.conf" -descriptor "/mnt/other-files/vrd/extreg.vrd"
Publish services ...
Публикация выполнена
docker exec web.demo.1cfresh.dev chown -R usr1cv8:grp1cv8 /var/www
docker exec web.demo.1cfresh.dev httpd -k graceful
Publish services ... done
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/smtl.cf /tmp/smtl.cf" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 CREATEINFOBASE "Srvr=srv;Ref=smtl;DBMS=PostgreSQL;DBSrvr=/tmp/postgresql/socket;DB=smtl;DBUID=postgres;LicDstr=Y;Locale=ru_RU;CrSQLDB=Y;SchJobDn=Y;" /UseTemplate /tmp/smtl.cf /Out "/mnt/create_ib_smtl.out"
Creating smtl is fihish. Duration:0:00:55.932761
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/other-files/cfe/api_1cfresh.cfe /tmp/api_1cfresh.cfe" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 DESIGNER /S "srv\smtl" /LoadCfg "/tmp/api_1cfresh.cfe" -Extension "api_1cfresh" /UpdateDBCfg /Out "/mnt/install_control_ext_smtl.out"
Installing control extension is fihish. Duration:0:00:07.979045
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/other-files/cfe/disable.epf /tmp/disable.epf" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 ENTERPRICE /S "srv\smtl" /Execute "/tmp/disable.epf" /Out "/mnt/disable_safe_mode_smtl.out"
Disabling safe mode for extensions is fihish. Duration:0:00:06.836624
docker exec web.demo.1cfresh.dev curl  -X POST http://localhost/int/smtl/hs/api.1cfresh/init
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:10 --:--:--     0Prepare all bases .
Initialization is fihish. Duration:0:00:10.836868
docker exec -t ras.demo.1cfresh.dev deployka scheduledjobs unlock -db smtl -db-user "Admin"
ИНФОРМАЦИЯ - Получаю список кластеров
ИНФОРМАЦИЯ - Поиск базы smtl в кластере Локальный кластер
ИНФОРМАЦИЯ - База smtl с ID: c9cbf656-cdfc-4c1f-98cf-001b193b47f7 найдена в кластере Локальный кластер
ИНФОРМАЦИЯ - Регламентные задания разрешены
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/sa.cf /tmp/sa.cf" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 CREATEINFOBASE "Srvr=srv;Ref=sa;DBMS=PostgreSQL;DBSrvr=/tmp/postgresql/socket;DB=sa;DBUID=postgres;LicDstr=Y;Locale=ru_RU;CrSQLDB=Y;SchJobDn=Y;" /UseTemplate /tmp/sa.cf /Out "/mnt/create_ib_sa.out"
Creating sa is fihish. Duration:0:00:17.801597
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/other-files/cfe/api_1cfresh.cfe /tmp/api_1cfresh.cfe" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 DESIGNER /S "srv\sa" /LoadCfg "/tmp/api_1cfresh.cfe" -Extension "api_1cfresh" /UpdateDBCfg /Out "/mnt/install_control_ext_sa.out"
Installing control extension is fihish. Duration:0:00:04.905770
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/other-files/cfe/disable.epf /tmp/disable.epf" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 ENTERPRICE /S "srv\sa" /Execute "/tmp/disable.epf" /Out "/mnt/disable_safe_mode_sa.out"
Disabling safe mode for extensions is fihish. Duration:0:00:04.850826
docker exec web.demo.1cfresh.dev curl  -X POST http://localhost/int/sa/hs/api.1cfresh/init
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0Prepare all bases ..
Initialization is fihish. Duration:0:00:05.169443
docker exec -t ras.demo.1cfresh.dev deployka scheduledjobs unlock -db sa -db-user ""
ИНФОРМАЦИЯ - Получаю список кластеров
ИНФОРМАЦИЯ - Поиск базы sa в кластере Локальный кластер
ИНФОРМАЦИЯ - База sa с ID: a9285c6f-c946-4afc-8fcd-51e5e3544073 найдена в кластере Локальный кластер
ИНФОРМАЦИЯ - Регламентные задания разрешены
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/am.cf /tmp/am.cf" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 CREATEINFOBASE "Srvr=srv;Ref=am;DBMS=PostgreSQL;DBSrvr=/tmp/postgresql/socket;DB=am;DBUID=postgres;LicDstr=Y;Locale=ru_RU;CrSQLDB=Y;SchJobDn=Y;" /UseTemplate /tmp/am.cf /Out "/mnt/create_ib_am.out"
Creating am is fihish. Duration:0:00:06.809159
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/other-files/cfe/api_1cfresh.cfe /tmp/api_1cfresh.cfe" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 DESIGNER /S "srv\am" /LoadCfg "/tmp/api_1cfresh.cfe" -Extension "api_1cfresh" /UpdateDBCfg /Out "/mnt/install_control_ext_am.out"
Installing control extension is fihish. Duration:0:00:02.854040
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/other-files/cfe/disable.epf /tmp/disable.epf" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 ENTERPRICE /S "srv\am" /Execute "/tmp/disable.epf" /Out "/mnt/disable_safe_mode_am.out"
Disabling safe mode for extensions is fihish. Duration:0:00:02.779421
docker exec web.demo.1cfresh.dev curl  -X POST http://localhost/int/am/hs/api.1cfresh/init
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Prepare all bases .
Initialization is fihish. Duration:0:00:00.586387
docker exec -t ras.demo.1cfresh.dev deployka scheduledjobs unlock -db am -db-user "Администратор"
ИНФОРМАЦИЯ - Получаю список кластеров
ИНФОРМАЦИЯ - Поиск базы am в кластере Локальный кластер
ИНФОРМАЦИЯ - База am с ID: 5ec436d6-3efd-4eb7-85ac-abcdfc8063bf найдена в кластере Локальный кластер
ИНФОРМАЦИЯ - Регламентные задания разрешены
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/sm.cf /tmp/sm.cf" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 CREATEINFOBASE "Srvr=srv;Ref=sm;DBMS=PostgreSQL;DBSrvr=/tmp/postgresql/socket;DB=sm;DBUID=postgres;LicDstr=Y;Locale=ru_RU;CrSQLDB=Y;SchJobDn=Y;" /UseTemplate /tmp/sm.cf /Out "/mnt/create_ib_sm.out"
Creating sm is fihish. Duration:0:01:18.951818
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/other-files/cfe/api_1cfresh.cfe /tmp/api_1cfresh.cfe" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 DESIGNER /S "srv\sm" /LoadCfg "/tmp/api_1cfresh.cfe" -Extension "api_1cfresh" /UpdateDBCfg /Out "/mnt/install_control_ext_sm.out"
Installing control extension is fihish. Duration:0:00:13.138837
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/other-files/cfe/УправлениеМС.cfe /tmp/УправлениеМС.cfe" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 DESIGNER /S "srv\sm" /LoadCfg "/tmp/УправлениеМС.cfe" -Extension "УправлениеМС" /UpdateDBCfg /Out "/mnt/install_sm_ext_sm.out"
Installing gate control extension is fihish. Duration:0:00:08.932062
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/other-files/cfe/disable.epf /tmp/disable.epf" && docker exec -t srv.demo.1cfresh.dev /opt/1C/v8.3/x86_64/1cv8 ENTERPRICE /S "srv\sm" /Execute "/tmp/disable.epf" /Out "/mnt/disable_safe_mode_sm.out"
Disabling safe mode for extensions is fihish. Duration:0:00:07.101296
docker exec web.demo.1cfresh.dev curl -d @/mnt/other-files/params.json -X POST http://localhost/int/sm/hs/api.1cfresh/init
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3631    0     0  100  3631      0    123  0:00:29  0:00:29 --:--:--     0Prepare all bases ...
Initialization is fihish. Duration:0:00:29.415627
docker exec -t ras.demo.1cfresh.dev deployka scheduledjobs unlock -db am -db-user "Администратор"
ИНФОРМАЦИЯ - Получаю список кластеров
ИНФОРМАЦИЯ - Поиск базы am в кластере Локальный кластер
ИНФОРМАЦИЯ - База am с ID: 5ec436d6-3efd-4eb7-85ac-abcdfc8063bf найдена в кластере Локальный кластер
ИНФОРМАЦИЯ - Регламентные задания разрешены
Prepare all bases ... done
docker exec -t db.demo.1cfresh.dev sh -c "/usr/bin/psql -U postgres -f /create_db_site.psql"
CREATE DATABASEite
CREATE ROLE
ALTER DATABASE
GRANT
Create db for site ... done
docker exec -t db.demo.1cfresh.dev sh -c "/usr/bin/psql -U postgres -f /create_db_forum.psql"
CREATE DATABASEorum .
CREATE ROLE
ALTER DATABASE
GRANT
Create db for forum ... done
docker-compose -f workdir/docker-compose.yml up -d nginx site
db.demo.1cfresh.dev is up-to-date
Creating forum.demo.1cfresh.dev ... done
Creating site.demo.1cfresh.dev  ... done
Creating nginx.demo.1cfresh.dev ... done
docker exec -t site.demo.1cfresh.dev /wait_site.sh
Tomcat is ready! ..
Waiting for site ... done
docker exec -t web.demo.1cfresh.dev curl --user Администратор: -X POST http://localhost/int/sm/hs/api.1cfresh/delete
Delete control extensionsm ... done
docker exec -t web.demo.1cfresh.dev curl --user Admin: -X POST http://localhost/int/smtl/hs/api.1cfresh/delete
Delete control extensionsmtl ... done
docker exec -t web.demo.1cfresh.dev curl -X POST http://localhost/int/sa/hs/api.1cfresh/delete
Delete control extensionsa ... done
docker exec -t web.demo.1cfresh.dev curl --user Администратор: -X POST http://localhost/int/am/hs/api.1cfresh/delete
Delete control extensionam ... done
docker exec -t web.demo.1cfresh.dev curl -F propertiesMap['site.url']=https://demo.1cfresh.dev -F propertiesMap['site.locale']=ru -F propertiesMap['site.media_directory']=/var/www/content/site_files/ -F propertiesMap['search.indexDir']=/var/www/content/searchIndex/ -F propertiesMap['ws.endpoint']=http://web/int/sm/ws/Subscriber -F propertiesMap['ws.endpoint.rest']="" -F propertiesMap['ws.endpoint.rest.timeout']=5000 -F propertiesMap['ws.publicUserName']=Anonymous -F propertiesMap['ws.publicUserPassword']= -F propertiesMap['ws.protectUserName']=ProtectedUser -F propertiesMap['ws.protectUserPassword']= -F propertiesMap['ws.am.endpoint']=http://web/int/am/ws/Availability -F propertiesMap['ws.am.username']=Reader -F propertiesMap['ws.am.password']=123Qwer -F propertiesMap['openid.oipEndpointUrl']=https://demo.1cfresh.dev/a/openid/e1cib/oid2op -F propertiesMap['viewsProperties.forumUrl']=https://1cfresh.sample/forum/ -F propertiesMap['viewsProperties.adminApplicationUrl']=https://demo.1cfresh.dev/a/adm/ -F propertiesMap['viewsProperties.mailto']=info@1cfresh.sample -F propertiesMap['viewsProperties.supportMailto']=support@1cfresh.sample -F propertiesMap['open.registration.ws.endpoint']=http://web/int/sm/ws/ExternalRegistration_1_0_0_1 -F propertiesMap['open.registration.user']=ExternalRegistration -F propertiesMap['open.registration.password']=123Qwer -F propertiesMap['open.registration.siteId']=1 -F propertiesMap['open.registration.sourceId']=1 -F submit= https://demo.1cfresh.dev/settings/edit_settings
Configurate site settings


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Strict//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html>
<head>
    <meta name="robots" content="noindex"/>
</head>
<body>




<!DOCTYPE html>
<html>
<head>
    <title>Мастер настройки сайта</title>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/resources/css/new/bootstrap.css"/>
    <link rel="stylesheet" href="/resources/css/new/style.css"/>
</head>
<body>
<div id="home" class="back-color-gray ledge-top2 ledge-bottom3 flexible-review-list">
    <div class="container">
        <div class="row">
            <div class="span9 offset1 well">
                <div class="row">
                    <div class="span7">
                        <h2>Мастер настройки сайта</h2>
                    </div>
                    <div class="span2">
                        <div class="small">Поддержка:</div>
                        <br>
                        <div class="small">8 (000) 000-00-00</div>
                        <br>

                        <div class="small"><a href="mailto:support@1cfresh.sample">support@1cfresh.sample</a></div>
                    </div>
                </div>
                <hr>


                <p class="navbar-text pull-right">Шаг 2 из 6</p>

                <h4>Настройки подключений к веб-сервисам менеджера сервиса</h4>

                <form method="POST" action="edit_settings?settingsPage=1" modelAttribute="propertiesMap"
                      accept-charset="UTF-8">

                    <div class="text">Укажите URL, логин и пароль для подключения сайта к API менеджера сервиса технологии 1cFresh.</div>

                        <div class="form-group offset-bottom1 ">

                            <label for="ws.endpoint" rel="tooltip" data-original-title="URL веб-сервиса Subscriber внутренней публикации Менеджера сервиса"><strong>ws.endpoint</strong></label>
                            <span style="color:red">*</span>
                            <input type="text" class="span9" id="ws.endpoint" name="propertiesMap['ws.endpoint']"
                                   value="http://web/int/sm/ws/Subscriber" placeholder="URL веб-сервиса Subscriber внутренней публикации Менеджера сервиса">
                        </div>

                        <div class="form-group offset-bottom1 ">

                            <label for="ws.endpoint.rest" rel="tooltip" data-original-title="URL REST-веб-сервиса Subscriber внутренней публикации Менеджера сервиса"><strong>ws.endpoint.rest</strong></label>

                            <input type="text" class="span9" id="ws.endpoint.rest" name="propertiesMap['ws.endpoint.rest']"
                                   value="" placeholder="URL REST-веб-сервиса Subscriber внутренней публикации Менеджера сервиса">
                        </div>

                        <div class="form-group offset-bottom1 ">

                            <label for="ws.endpoint.connectTimeout" rel="tooltip" data-original-title="Timeout установления соединения к веб-сервису Subscriber внутренней публикации Менеджера сервиса (задается в миллисекундах)"><strong>ws.endpoint.connectTimeout</strong></label>

                            <input type="text" class="span9" id="ws.endpoint.connectTimeout" name="propertiesMap['ws.endpoint.connectTimeout']"
                                   value="5000" placeholder="Timeout установления соединения к веб-сервису Subscriber внутренней публикации Менеджера сервиса (задается в миллисекундах)">
                        </div>

                        <div class="form-group offset-bottom1 ">

                            <label for="ws.endpoint.socketTimeout" rel="tooltip" data-original-title="Timeout доступа к веб-сервису Subscriber внутренней публикации Менеджера сервиса (задается в миллисекундах)"><strong>ws.endpoint.socketTimeout</strong></label>

                            <input type="text" class="span9" id="ws.endpoint.socketTimeout" name="propertiesMap['ws.endpoint.socketTimeout']"
                                   value="5000" placeholder="Timeout доступа к веб-сервису Subscriber внутренней публикации Менеджера сервиса (задается в миллисекундах)">
                        </div>

                        <div class="form-group offset-bottom1 ">

                            <label for="ws.publicUserName" rel="tooltip" data-original-title="Пользователь Менеджера сервиса, предназначенный для вызова методов веб-сервиса Subscriber, не требующих авторизации пользователя"><strong>ws.publicUserName</strong></label>

                            <input type="text" class="span9" id="ws.publicUserName" name="propertiesMap['ws.publicUserName']"
                                   value="Anonymous" placeholder="Пользователь Менеджера сервиса, предназначенный для вызова методов веб-сервиса Subscriber, не требующих авторизации пользователя">
                        </div>

                        <div class="form-group offset-bottom1 ">

                            <label for="ws.publicUserPassword" rel="tooltip" data-original-title="Пароль пользователя Менеджера сервиса, предназначенного для вызова методов веб-сервиса"><strong>ws.publicUserPassword</strong></label>

                            <input type="text" class="span9" id="ws.publicUserPassword" name="propertiesMap['ws.publicUserPassword']"
                                   value="" placeholder="Пароль пользователя Менеджера сервиса, предназначенного для вызова методов веб-сервиса">
                        </div>

                        <div class="form-group offset-bottom1 ">

                            <label for="ws.protectUserName" rel="tooltip" data-original-title="Пользователь Менеджера сервиса, предназначенный для вызова методов веб-сервиса Subscriber, требующих авторизации пользователя"><strong>ws.protectUserName</strong></label>

                            <input type="text" class="span9" id="ws.protectUserName" name="propertiesMap['ws.protectUserName']"
                                   value="ProtectedUser" placeholder="Пользователь Менеджера сервиса, предназначенный для вызова методов веб-сервиса Subscriber, требующих авторизации пользователя">
                        </div>

                        <div class="form-group offset-bottom1 ">

                            <label for="ws.protectUserPassword" rel="tooltip" data-original-title="Пароль пользователя Менеджера сервиса, предназначенного для вызова методов API веб-сервиса Subscriber, требующих авторизации"><strong>ws.protectUserPassword</strong></label>

                            <input type="text" class="span9" id="ws.protectUserPassword" name="propertiesMap['ws.protectUserPassword']"
                                   value="" placeholder="Пароль пользователя Менеджера сервиса, предназначенного для вызова методов API веб-сервиса Subscriber, требующих авторизации">
                        </div>

                    <div class="row offset-bottom1">
                        <div class="span3">

                            <button id="back_button" type="button" name="go_back" class="btn btn-default btn-block"
                                    onclick="history.go(-1);return true;">Назад</button>
                        </div>
                        <div class="span3">


                                <button id="validationButton" type="button" name="validation" class="btn btn-default btn-block"
                                        onclick="doValidation()">Проверить подключение</button>

                        </div>
                        <div class="span3">

                            <button id="next_block" type="submit" name="submit" class="btn btn-primary pull-right">
                                Сохранить и продолжить
                            </button>
                        </div>

                    </div>
                    <div class="row">
                        <p class="text-center"><b id="result_text"></b></p>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script src="/resources/js/new/jquery-1.10.2.js"></script>
<script src="/resources/js/new/bootstrap.js"></script>


        <script type="text/JavaScript" src="/resources/js/settings/ValidateBlock.js"></script>


<script type="text/javascript">
    $(function(){
        $('[rel="tooltip"]').tooltip();
    });
</script>
</body>
</html>
</body>
</html>
docker exec -t web.demo.1cfresh.dev curl https://demo.1cfresh.dev/settings/finish_configuration
docker exec -t web.demo.1cfresh.dev curl -F id=25 -F key=ManualRegistration -F description="Включение регистрации на сайте без выбора партнера (код приглашения высылается автоматически)" -F enabled=true -F _enabled=on https://demo.1cfresh.dev/admin/features/25/edit
docker exec -t web.demo.1cfresh.dev curl -F id=2 -F key=openid -F description="Включение работы OpenID на сайте" -F enabled=true -F _enabled=on https://demo.1cfresh.dev/admin/features/2/edit
docker exec -t web.demo.1cfresh.dev curl -F _enableDemo=on -F _showVideo=on -F _userVisible=on -F briefDescription="БТС" -F displayOrder=0 -F fullDescription="БТС" -F id=smtl -F possibilities="БТС" -F screenshotCount=0 -F title="Библиотека технологии сервиса" -F userVisible=true -F videosPageTitle="БТС" https://demo.1cfresh.dev/admin/solutions/add
Configurate site settings ... done
docker exec -t web.demo.1cfresh.dev curl --user Администратор: https://demo.1cfresh.dev/a/adm/hs/docker_control/update_appgate
false - {ОбщийМодуль.ШлюзыПриложений.Модуль(1213)}: Не удалось определить URL, который должен использоваться шлюзом приложений
для выполнения вызовов в менеджер сервиса.
Необходимо указать значение одной из следующих константы
АдресДляПодключенийШлюзовПриложений (или значение константы
ВнутреннийАдресЭтогоПриложения, если адрес для подключения шлюзов приложений
Initialization gate ... done я подключения прикладных информационных баз)!Initialization gate .
Fresh started Duration: 0:05:44.736171

**Comment by svok2005** [comment]
https://yadi.sk/i/3Dy0zaJO5FVi1g

**Comment by WizaXxX** [comment]
Скажите пожалуйста какую версию МС пытаетесь поднять?
И еще скриншот Главное -> Настройки конфигурации -> Настройки доступа

**Comment by svok2005** [comment]
https://yadi.sk/i/pIYqoL1hZtPVjg
Менеджер сервиса, редакция 1.1 (1.1.2.17)

**Comment by WizaXxX** [comment]
У вас по какой то причине не выполнился данный код
![image](https://user-images.githubusercontent.com/8429673/118159844-37089b80-b426-11eb-9c67-87012863c8bb.png)
Посмотрите ошибки в ЖР Менеджера сервиса.
И есть ли у вас элементы в справочниках "Менеджеры сервиса", "Агенты сервиса" ?

**Comment by svok2005** [comment]
https://yadi.sk/i/HP6sN8S2x_8S2A
https://yadi.sk/i/T3PHNzhuqY34hw

**Comment by svok2005** [comment]
Реквизит справочника переименован в УдалитьНаПоддержке

**Comment by WizaXxX** [comment]
Сделал исправление.
Обновите расширение other_files/cfe/api_1cfresh.cfe и запустите скрипт start снова.

**Comment by svok2005** [comment]
Спасибо, заработало!
