### ISSUE TITLE
Ошибка развертывания

### ISSUE THREAD

**Issue by svok2005** [1C-Company/docker_fresh#21]
После развертывания стенда, при добавлении нового приложения выдает ошибку.  При анализе было выявлено, что в информационной базе Работа в модели сервиса не заполнился Web-адрес управения и Пароль пользователя управления. В случае ручного добавления адреса http://web/int/smtl не проходит проверка подключения при записи.
https://yadi.sk/i/xgOMLt01vSYxtA
https://yadi.sk/i/FNqTN4zwt5W9iA
https://yadi.sk/i/JCiFg--AHFNe4A

**Comment by WizaXxX** [comment]
Похоже что вы не установили расширение smtl. В комплекте поставки БТС есть расширение. Его нужно разместить рядом с файлом конфигурации и назвать smtl.cfe

**Comment by svok2005** [comment]
Спасибо! Сработало!

Новая проблема. Приложение готовится уже минут 20
https://yadi.sk/i/h8vOH9-JFF6wxg

**Comment by WizaXxX** [comment]
Нужно смотреть что в ЖР базы по ошибкам, в которой создаётся приложение и что в ЖР Менеджера сервиса

**Comment by svok2005** [comment]
В ЖР МС и приложения ошибок нет

**Comment by WizaXxX** [comment]
Хм... очень странно. А что тогда в справочнике сообщения обмена в МС.
И в справочниках Очередь заданий и Сообщения обмена в БТС?

**Comment by svok2005** [comment]
При анализе обнаружил ошибку
https://yadi.sk/i/koeGpVpyXwIe0Q

**Comment by WizaXxX** [comment]
Расскажите пожалуйста про то, каким образом вы поднимаете стенд (На виртуалке, или на локальном ПК, win или linux и т.д.)
Суть показанного на крине заключается в следующем. В каждую базу в контуре ставится расширение api_1cfresh у которого есть http сервис и метод который возвращает информацию об ИБ. В вашем случае почему то не получилось достучаться до этой базы. 
Еще будет полезна строка с помощью которой вы запускаете скрипт start

**Comment by svok2005** [comment]
Стенд поднимаю на виртуалке
OS Windows, Среда виртуализации VMware Workstation 16

ВМ: Linux 1cfresh 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Comment by svok2005** [comment]
Еще увидел что в ИБ Менеджера сервиса не указаны WEB-Адреса 
https://yadi.sk/i/tl6Cz0MV72q8eg

**Comment by svok2005** [comment]
python3 start.py -new -h demo

**Comment by svok2005** [comment]
Проблема в адресом сервера. Он пустой
https://yadi.sk/i/RXaTOlNae6LUFA

**Comment by svok2005** [comment]
Проблему с добавлением Приложений решил. В ИБ МС была включена блокировка регламентных заданий.

**Comment by WizaXxX** [comment]
Странно, она должна отключаться.
а проблема с тем что веб адреса не указаны?

**Comment by svok2005** [comment]
По Web адресам тоже разобрался. Ошибка была когда попытка добавления в справочник ИБ конфигурации Менеджер доступности. А у него в файте param.json значение Сервер пустое. Добавил в расширение api_1cfresh проверку на заполненость параметра Сервер. https://yadi.sk/i/3AIOqf7sE-vRIQ

**Comment by WizaXxX** [comment]
Очень странно, адреса должны заполняться для всех баз кроме Менеджера сервиса.
