### ISSUE TITLE
Ошибка скрипта start.py

### ISSUE THREAD

**Issue by DmitrySeleznev** [1C-Company/docker_fresh#24]
Добрый день.
При запуске срипта
sudo python3 start.py -new -h demo -debug sudo python3 start.py -new -h demo -debug
возникает ошибка
лог (частично) ....
Publish services ... done
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/smtl.cf /tmp/smtl.cf" && docker exec -t srv.demo.1cfresh.dev /opt/1cv8/x86_64/8.3.19.1522/1cv8 CREATEINFOBASE "Srvr=srv;Ref=smtl;DBMS=PostgreSQL;DBSrvr=/tmp/postgresql/socket;DB=smtl;DBUID=postgres;LicDstr=Y;Locale=ru_RU;CrSQLDB=Y;SchJobDn=Y;" /UseTemplate /tmp/smtl.cf /Out "/mnt/create_ib_smtl.out"
Creating smtl is fihish. Duration:0:01:16.133012
docker exec srv.demo.1cfresh.dev sh -c "cp /mnt/other-files/cfe/api_1cfresh.cfe /tmp/api_1cfresh.cfe" && docker exec -t srv.demo.1cfresh.dev /opt/1cv8/x86_64/8.3.19.1522/1cv8 DESIGNER /S "srv\smtl" /LoadCfg "/tmp/api_1cfresh.cfe" -Extension "api_1cfresh" /UpdateDBCfg /Out "/mnt/install_control_ext_smtl.out"
sh: /sbin/ip: No such file or directory
[log_fresh_start.txt](https://github.com/1C-Company/docker_fresh/files/8451426/log_fresh_start.txt)

Сам файл присутствует в папке \docker_fresh\other_files\cfe\api_1cfresh.cfe

Подскажите, пожалуйста, если что не так.

**Comment by WizaXxX** [comment]
Подскажите пожалуйста все вводные, на какой системе разворачиваете, как файлы дистрибутивов подкладываете и т.д

**Comment by DmitrySeleznev** [comment]
Виртуальная машина VirtualBox. Ubuntu Server 20.04. 
Папка Distr
  appgate_1.1.1.14_all.deb
  site_1.2.22.zip
  forum_1.0.42.1.zip
  client_8_3_19_1522.rpm64.tar.gz
  rpm64_8_3_19_1522.tar.gz
  .gitignore
  sm.cf (SM_1_1_14_13_setup1c)
  smtl.cf (SMTL_2_0_9_17_setup1c)
  smtl.cfe
  sa.cf (SA_1_1_14_4_setup1c)
  am.cf (AM_1_1_1_4_setup1c)

**Comment by WizaXxX** [comment]
Внес некоторые исправления. Теперь этой ошибки нет.
Если все таки развертывание зависнет, можно подключить к контейнеру по vnc и посмотреть что там 1С пишет

**Comment by DmitrySeleznev** [comment]
Стенд развернулся. Функциональность посмотреть сегодня не получилось. Смущают Warning при подключении расширений api_1cfresh.cfe к базам (** (1cv8:280): WARNING **: 15:35:43.134: Could not connect: Connection refused). Полный лог во вложении
[log_fresh_start2.txt](https://github.com/1C-Company/docker_fresh/files/8465692/log_fresh_start2.txt)
.

**Comment by WizaXxX** [comment]
Вроде ничего страшного в нем нет, т.к. тоже у себя на стенде вижу это иногда, но все работает отлично.

**Comment by DmitrySeleznev** [comment]
Ок. Спасибо за помощь.
