### ISSUE TITLE
Ошибка развертывания

### ISSUE THREAD

**Issue by svok2005** [1C-Company/docker_fresh#28]
При сборке образов (python3 install.py -v 8.3.17.2306 --debug) выдает ошибку:
Cannot open: http://1c.postgrespro.ru/pg1c-9.6/keys/postgrespro-1c-9.6.centos.yum-9.6-0.3.noarch.rpm. Skipping.
Что делать для устранения ошибки?

**Comment by shihun78** [comment]
Напишите, пожалуйста, где можно взять postgrespro-1c-9.6.centos.yum-9.6-0.3.noarch.rpm или другой подходящий пакет?

**Comment by svok2005** [comment]
Решил вопрос заменой ссылки на  http://repo.postgrespro.ru/pg1c-9.6/keys/postgrespro-1c-9.6.centos.yum-9.6-0.3.noarch.rpm

**Comment by shihun78** [comment]
> Решил вопрос заменой ссылки на http://repo.postgrespro.ru/pg1c-9.6/keys/postgrespro-1c-9.6.centos.yum-9.6-0.3.noarch.rpm

Спасибо!
