### ISSUE TITLE
for java:8-jre not found: manifest unknown: manifest unknown

### ISSUE THREAD

**Issue by lael1717** [1C-Company/docker_fresh#30]
Sending build context to Docker daemon  4.986MB
Step 1/5 : FROM java:8-jre
manifest for java:8-jre not found: manifest unknown: manifest unknown
Building gate ... error

**Comment by WizaXxX** [comment]
Попробуйте заменить в Dockerfile 
`java:8-jre`
на
`openjdk:8-jre`

**Comment by lael1717** [comment]
здравствуйте! и вот что дает...
![image](https://user-images.githubusercontent.com/114162009/195283999-f9029e80-ac87-4418-a844-fa7c55f5e371.png)
